### PR TITLE
Pause updates when printing paused for M600 or filament runout

### PR DESCRIPTION
**Pull request by bennymamo**
Pause updates when printing paused for M600 or filament runout

### CODE REVIEW

**Comment by bennymamo** [comment]
You will need to triple check my code, as already mentioned, I am still green here.

**Comment by tpmullan** [comment]
Looks like it should work to me.  I will merge to master and run some tests there.  If all goes well I will do a minor release with theses changes so everyone gets the updates.  Thanks for the pull request!

**Comment by tpmullan** [comment]
Closes #21

**Comment by bennymamo** [comment]
@tpmullan Did you manage to do some tests yet? did it work fine for you? When do you think you will make the minor release please?

**Comment by tpmullan** [comment]
This should be in version 0.2.7

Thanks for the contribution!

**Pull request merged**
